# Built with Jekyll 3.6.0

# Setup
title:               Encyclopedia of the Dog
tagline:             'An annotated digital edition of <i>Between Dog and Wolf</i> by Sasha Sokolov'
description:         'An annotated digital edition of Between Dog and Wolf by Sasha Sokolov'
url:                 'http://digbmc.github.io'
baseurl:             '/dogopedia-dev'

# About/contact
author:
  name:              Digital Scholarship at Bryn Mawr College
  url:               https://digitalscholarship.brynmawr.edu/
  email:             digitalscholarship@brynmawr.edu

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: dog

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: false
  chapters:
    output: true
    
# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       false
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor
  - ed..gemspec
  - Gemfile
  - Gemfile.lock
  - backstop_data
  - backstop.json
  - notes

# Theme
# (Used for local or custom-server deployments)
# Uncomment the `theme` line if using the Ed. theme gem on your own computer or server.
# See https://jekyllrb.com/docs/themes/
# theme: "ed."

# Remote Theme
# (Used only for GitHub deployments)
# See https://help.github.com/en/articles/adding-a-jekyll-theme-to-your-github-pages-site
remote_theme: minicomp/ed
